## Select environment via: Run with: [dev|...]
## See: TrailFinder.Api/http-client.env.json

### Get all trails
GET {{hostAddress}}/api/v1/trails
Accept: application/json

### Get a specific trail by id
GET {{hostAddress}}/api/v1/trails/{{trailId}}
Accept: application/json

### Get a specific trail by slug
GET {{hostAddress}}/api/v1/trails/esja-ultra-marathon-43
Accept: application/json

### Get all races
GET {{hostAddress}}/api/v1/races
Accept: application/json

### Get a specific race by id
GET {{hostAddress}}/api/v1/races/{{raceId}}
Accept: application/json

### Get a specific race by slug
GET {{hostAddress}}/api/v1/races/laugavegur-ultra
Accept: application/json

### Get all locations
GET {{hostAddress}}/api/v1/locations
Accept: application/json

### Get a specific location by id
GET {{hostAddress}}/api/v1/locations/{{locationId}}
Accept: application/json

### Get a specific location by slug
GET {{hostAddress}}/api/v1/locations/landmannalaugar
Accept: application/json

### When trail/s do not exist

### Guid does not exist
GET {{hostAddress}}/api/v1/trails/1.2.3.4
Accept: application/json

### slug does not exist
GET {{hostAddress}}/api/v1/trails/slug-does-not-exist
Accept: application/json

### Update trail info by id
PUT {{hostAddress}}/api/v1/trails/{{trailId}}
Content-Type: application/json

{
  "distanceMeters": 15500.50,
  "elevationGainMeters": 850.0,
  "difficultyLevel": "extreme",
  "updatedBy": "{{userId}}"
}


### When validation error occur

### guid is not the right length
GET {{hostAddress}}/api/v1/trails/366-66fba19c4240
Accept: application/json


#############################################################
### GPX File Operations (Controller: GpxFilesController) ###
#############################################################

### Upload GPX file for a specific trail
# Replace {{trailId}} with an actual valid Trail ID
# Replace path/to/your/file.gpx with the actual local path to a GPX file
POST {{hostAddress}}/api/v1/trails/{{trailId}}/gpx-file/upload
Content-Type: multipart/form-data; boundary=----------Boundary12345

------------Boundary12345
Content-Disposition: form-data; name="file"; filename="laugavegur-ultra.gpx"
Content-Type: application/gpx+xml

< C:\dev\trailfinder\TrailFinder.DB\supabase\seeds\gpx-file\laugavegur-ultra.gpx
------------Boundary12345--


### Get GPX file metadata for a specific trail
# This fetches the metadata stored in your gpx_files table // TODO: add this endpoint
GET {{hostAddress}}/api/v1/trails/{{trailId}}/gpx-file/metadata
Accept: application/json


### Download GPX file for a specific trail
# This fetches the actual GPX file content from Supabase Storage
GET {{hostAddress}}/api/v1/trails/{{trailId}}/gpx-file/download
Accept: application/gpx+xml
